version: '3.8'
services:
  api:
    build:
      context: ./api_project
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./front_project
    ports:
      - "80:80"